---
apiVersion: v1
kind: Service
metadata:
  name: abc-project-nodeport-service
spec:
  selector:
    app: abc-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
